### PR TITLE
Trying to get this working

### PR DESCRIPTION
**Pull request by gallais**
I'm having issues getting the VM built.
I'll push more fixes if I can figure more things out.

### CODE REVIEW

**Comment by gallais** [comment]
Hmm. Some `"<enter><wait5>",` seem to be skipping crucial steps. :thinking: 

Edit: yep seems to all work now after that 3rd commit

**Comment by gallais** [comment]
Hmmm now the example does not work. May be because of another missing dependency.

**Comment by gallais** [comment]
Got the example working too!

**Comment by gallais** [comment]
Successful CI build! https://github.com/gallais/packer-idris/actions/runs/3830319713/jobs/6518031008

I'm happy with the current setup @jfdm

**Comment by jfdm** [comment]
Thanks for this, it is much appreciated. (The incantation for bootstrapping is hard to get right!)

I am sorry that it was not quite usable from a fresh clone. I made many changes to this project in the run-up to the festive break to get some working artifacts.

Again thanks for the push! and the CI.

**Comment by gallais** [comment]
Thanks for the original project! It was easy enough to figure out what the successive
issues were, and a lot less work than starting from scratch I'm sure!

**Pull request merged**
